version: 0.2
phases:
  install:
    commands:
      - wget -N https://chromedriver.storage.googleapis.com/104.0.5112.20/chromedriver_linux64.zip -P ~/
      - unzip ~/chromedriver_linux64.zip -d ~/
      - rm ~/chromedriver_linux64.zip
      - mv -f ~/chromedriver /usr/local/bin/chromedriver
      - chown root:root /usr/local/bin/chromedriver
      - chmod 0755 /usr/local/bin/chromedriver


        # Install chrome broswer
      - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - apt-get -y update
      - apt-get -y install google-chrome-stable
  build:
    commands:
      - echo Stating build phase
      - mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
  post_build:
    commands:
      - echo Post Build Started successfully on `date`
      - aws s3 cp logs/Results/GlobalReport.html s3://codepipeline-ap-south-1-781882469030
      - echo Build completed on `date`
artifacts:
  files:
      - logs/**/*
