version: 0.2
phases:
  install:
    commands:
      - wget -N https://chromedriver.storage.googleapis.com/104.0.5112.20/chromedriver_linux64.zip -P ~/
      - unzip ~/chromedriver_linux64.zip -d ~/
      - rm ~/chromedriver_linux64.zip
      - mv -f ~/chromedriver /usr/local/bin/chromedriver
      - chown root:root /usr/local/bin/chromedriver
      - chmod 0755 /usr/local/bin/chromedriver


        # Install chrome broswer
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - sudo yum install ./google-chrome-stable_current_*.rpm
  build:
    commands:
      - echo Stating build phase
      - mvn clean test
